services:
  web:
    build: .
    ports:
      - '80:80'
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
      - LANGFUSE_BASEURL=${LANGFUSE_BASEURL}
      - SUPABASE_PRIVATE_KEY=${SUPABASE_PRIVATE_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - TW_IDENTITY_TOKEN=${TW_IDENTITY_TOKEN}
    volumes:
      - .:/code
